Add controllers
DM-student/java-shareit pull request #1
Opened 2023-05-21 03:16 UTC by DM-student

Здравствуйте! Пока проект выглядит суховато, но если утвердят его структуру - я приступлю к добавлению тестов и прочего.

И да, был бы рад иметь возможность исправить некоторые недочёты во время последующей разработки, дабы до "продакшена" всё исправить не застревая на этом ТЗ.

2023-05-22 09:05 UTC, LexLippi requested changes
Привет!

Неплохая работа, но есть некоторое количество замечаний, которое надо исправить!

Желаю удачи!

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + */
Такие комментарии следует удалять после выполнения

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private long receiverId = Long.MIN_VALUE;
Зачем здесь инициализация полей некорректными значениями?

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/Storage.java
> +    // сделать специфичное действие или что-то в этом роде.
Лучше не делать такого заранее. Объясню почему, попытка предугадать дальнейшие требования часто заканчивается плачевно, так как мы делаем ту работу, которая впоследствии никому не пригодится, так как вероятность угадать, как проект будет развиваться в дальнейшем довольно низкая. Может например, измениться подход к архитектуре в целом (и надо будет переходить со слоистой на гексагональную).

А поддержка неиспользуемого кода часто занимает много времени у разработчиков, в результате чего многие проекты развиваются медленее, чем хотелось бы.

Для описания данной проблемы есть принцип KISS, которой часто используется при разработке ПО:
https://en.wikipedia.org/wiki/KISS_principle

К тому же сортировку правильнее проводить на уровне сервиса, а не хранилища (если набор данных тот же самый). Ну и использовать массив строк в качестве аргументов для метода хранилища довольно странная затея. Вместо массива всегда лучше использовать список. Так как это массив строк, то скорее всего там будет набросан мусор из аргументов, который хранилище должно будет распарсить, но это не его задача. Оно утилитарно, сохраняет, обновляет и возвращает данные по некоторым признакам.

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/Storage.java
> +    T upload(T obj);
Странное название для метода, так как ты используешь названия `update`, `delete`, это похоже на `CRUD`-подход, тогда метод должен называться `create`, а не `upload`:
https://en.wikipedia.org/wiki/Create,_read,_update_and_delete

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        return null;
Возвращать `null` в таких ситуациях очень плохо, это может породить `NullPointerException`, в дальнейшем коде (который мог писать другой программист, и не предполагать, что в данном поле допустимо `null`-значение). По возможности лучше всегда использовать исключение

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +            // Nothing really.
Почему же ничего?
Пользователь, который вызывал наш метод для установки идентификатора владельца наверняка хочет знать произошла вставка или случилась ошибка. А так получается, что даже если произошла ошибка, он будет думать, что все корректно.

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +            throw new NotFoundExceptionForHandler("Предмет не найден.", "id#" + id);
Оно не должно называться `forHandler`. Хранилище никоим образом не представляет, как с ним работают снаружи. Это может быть веб-сервис, скрипт на сервере, что угодно, оно не обязательно предполагаеи наличия `handler`.

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +                    getItemOwnerId(sqlRows.getLong("id")),
Вот здесь ты сделаешь `N`-запросов, где `N`-количество записей в твоей таблице. При помощи `join` можно получить данные одним запросом. Это большая разница с точки зрения перфоманса твоего кода, при больших `N`

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        obj.setId(lastId + 1);
СУБД должна сама заниматься генерированием идентификатора, это ее задача

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        return text.toLowerCase().replaceAll("[^а-яa-z]", "");
Пробелы тоже убираем?

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        log.warn("getTextForSearch(obj.getDescription()) = {}", getTextForSearch(obj.getDescription()));
Это что за предупреждение?

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        get(obj.getId());
Зачем?

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +    }
Поэтому я и говорил, что лучше не придумывать себе методы заранее :)

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +                throw new IllegalArgumentException("specialGet получил неверный ключ операции.");
1. Как я уже говорил такая работа с аргументами это не дело хранилища
2. Гораздо лучше сделать это отдельными методами, так как при дальнейшем увеличении количества аргументов и их значений этот метод станет `GOD`-методом.

https://en.wikipedia.org/wiki/God_object

3. Появление таких аргументов означает, что все кто работают с проектом должны обладать тайным знанием о том, как их формировать для каждого случая, что абсолютно нереализуемо.

2023-05-22 09:05 UTC, LexLippi commented on src/main/resources/application.properties
>  #---
Удаляем такого рода комментарии

2023-05-22 09:05 UTC, LexLippi commented on src/main/resources/schema.sql
> +        name_for_searching VARCHAR(32) NOT NULL, -- это поможет ПОЛНОСТЬЮ перенести поиск на базу данных.
Зная, какую СУБД мы используем можно обойтись ее функционалом и не дублировать данные.

2023-05-22 09:05 UTC, LexLippi commented on src/main/resources/schema.sql
> +        id BIGINT NOT NULL PRIMARY KEY,
Идентификатор должен быть генерируемым самой СУБД

2023-05-22 09:05 UTC, LexLippi commented on src/main/resources/schema.sql
> +        email VARCHAR(320) NOT NULL,
`unique`?

2023-05-22 09:05 UTC, LexLippi commented on src/main/resources/schema.sql
> +        name VARCHAR(64) NOT NULL
`unique`?

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/utility/ErrorHandler.java
> +        if (e.getClass() == ProvidedDataExceptionForHandler.class) {
1. можно же `instanceOf` использовать
2. или `switch-case`

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/model/User.java
> + */
Подобного рода комментарии

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        return storage.getAll().stream().map(u -> mapper.mapToDto(u, true)).collect(Collectors.toList());
в лямбдах переменные такие же полноценные, как и в остальном коде, поэтому не следует давать им однобуквенные названия

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        return mapper.mapToDto(storage.upload(newUser), true);
Точно параметр необходим, если ты его везде в `true` устанавливаешь?

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        oldUser.mergeFrom(newUser);
Зачем такая сложная логика не очень понял, хотелось бы пояснений

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserController.java
>   */
Удалем комментарии

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> + */
Комментарий

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private long ownerId = Long.MIN_VALUE;
Зачем инициализируем неверными полями?

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto get(@PathVariable Long id) {
Для идентификаторов не помешает аннотация `@Positive`

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/UserStorage.java
> +        // Как я понимаю, если пользователь удалён - нужно удалить все его вещи.
Да, но это задача сервиса, а не хранилища.

2023-05-22 09:05 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/UserStorage.java
> +public class UserStorage implements Storage<User> {
Замечания аналогичные `ItemStorage`

2023-05-22 14:42 UTC, DM-student commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private long receiverId = Long.MIN_VALUE;
Там была идея одна, это сейчас не фигурирует в ТЗ, ибо этого ещё не дошли.

2023-05-22 14:50 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/Storage.java
> +    // сделать специфичное действие или что-то в этом роде.
проблема уровня сервиса в том, что нужно сначала выгрузить всё из БД в память, а лишь потом совершать махинации. С небольшими проектами это ещё нормально, но если БД будет на много-гигов, то будут наверное проблемы.

2023-05-22 14:50 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/Storage.java
> +    T upload(T obj);
Исправил

2023-05-22 15:00 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        obj.setId(lastId + 1);
А как мне тогда получить генерируемый id?

2023-05-22 15:00 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        return text.toLowerCase().replaceAll("[^а-яa-z]", "");
Да. В этом и была задумка.

2023-05-22 15:01 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        log.warn("getTextForSearch(obj.getDescription()) = {}", getTextForSearch(obj.getDescription()));
Ой, это я на фазе отладки оставил.

2023-05-22 15:03 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        get(obj.getId());
Проверить наличие... Если нет - выкинет ошибку "not found"

2023-05-22 15:07 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +                throw new IllegalArgumentException("specialGet получил неверный ключ операции.");
Согласен, но не совсем. Этот "GOD-метод" будет лишь для хранилища. Все какие-то серьёзные и конкретные действия будут уже в сервисах и прочем.

2023-05-22 15:11 UTC, DM-student commented on src/main/resources/schema.sql
> +        name_for_searching VARCHAR(32) NOT NULL, -- это поможет ПОЛНОСТЬЮ перенести поиск на базу данных.
У меня весьма специфичный способ поиска, ибо я делал максимально просто и быстро. Иначе мне нужно будет делать очень сложное регулярное выражение и танцевать с бубном, формируя запрос в SQL.

2023-05-22 15:11 UTC, DM-student commented on src/main/resources/schema.sql
> +        id BIGINT NOT NULL PRIMARY KEY,
Если подскажете как получить ключ после создания объекта - сделаю всё в СУБД.

2023-05-22 16:14 UTC, DM-student commented on src/main/resources/schema.sql
> +        email VARCHAR(320) NOT NULL,
Надо добавить, да.

2023-05-22 16:16 UTC, DM-student commented on src/main/java/ru/practicum/shareit/utility/ErrorHandler.java
> +        if (e.getClass() == ProvidedDataExceptionForHandler.class) {
Свич - работает только с примитивами, да и я его не очень люблю из-за его ограничений.

2023-05-22 16:21 UTC, DM-student commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        return mapper.mapToDto(storage.upload(newUser), true);
Нет, не везде. Во время маппинга ДТОшек - я, например, в списке предметов пользователя вывожу не полную информацию. Когда этот параметр стоит на false - объекты не отображают другие объекты которые в них находятся (например владельца или список предметов)

2023-05-22 16:25 UTC, DM-student commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        oldUser.mergeFrom(newUser);
Очень простая логика. Создаётся новый юзер согласно объекту запроса. Берётся из БД "старый" юзер. В старого юзера мержиться новый юзер (Смысл в том, что если некоторые поля - нуль, то они не будут вмержены и значение останется старым). После уже старый юзер, в которого мержили - отправляется в БД.

2023-05-22 16:26 UTC, DM-student commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private long ownerId = Long.MIN_VALUE;
Это вообще остаток от изначального, весьма неудачного концепта. Я уже убрал это.

2023-05-22 16:27 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/UserStorage.java
> +        // Как я понимаю, если пользователь удалён - нужно удалить все его вещи.
Окей.

2023-05-22 16:35 UTC, DM-student commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto get(@PathVariable Long id) {
Так оно же просто ничего не найдёт по отрицательному ID и выкинет 404. А создать с отрицательным Id человек не сможет.

2023-05-22 16:51 UTC, DM-student commented
Вновь здравствуйте! Я в некоторые комментарии к коду оставил не-заресолвлеными и там либо ответил, либо спросил что-то, буду рад, если прочитаете.

Также хочу попросить вас, что если будут какие-то недочёты по мелочи - то по возможности напишите о них и примите проект. Всё равно следующее ТЗ будет с этим же проектом, так что я к следующему ТЗ всё подлатаю, а то задерживаться не очень хочу.

2023-05-23 07:21 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/Storage.java
> +    // сделать специфичное действие или что-то в этом роде.
Тогда манипуляции будут производиться с СУБД, в слое-репозитории, будут написаны специальные методы в интерфейсе, с отдельной логикой получения и сортировки данных.

2023-05-23 07:24 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto get(@PathVariable Long id) {
Здесь некоторая абстракция на уровне слоев должна сработать. Твой контроллер не должен знать, как устроен сервис и полагаться на то, что он корректно обработает некорректные данные. Все наши слои должны работать исходя из того, что там находятся корректные данные. А корректность обеспеивает входной слой, в данном случае - контроллер

2023-05-23 07:24 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto get(@PathVariable Long id) {
Пока можешь не править, но на будущее так делать правильнее

2023-05-23 07:38 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Оставил пояснения к старым комментариям.

Желаю удачи, там вроде немного доработок осталось!

2023-05-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/Storage.java
> +    // сделать специфичное действие или что-то в этом роде.
Более того, если у тебя методу будет требоваться просто сортировка, то значит ты в любом случае выгрузишь все данные, так что сортировать можно в сервисе. Может добавиться пагинация, но тогда это отдельный метод с отдельными параметрами и логикой

2023-05-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +            // уже выполняет задачу по ограничению добавления дубликата.
Задачу безусловно, но пользователь на сайте например, который создавал вещь хочет увидеть человекочитаемую ошибку, а не просто молча не изменившийся список. Он хочет понимать почему ничего не произошло, а значит нам надо пробросить ошибку, а не тактично промолчать

2023-05-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        return null;
Напоминаю

2023-05-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        obj.setId(lastId + 1);
https://www.baeldung.com/spring-jdbc-autogenerated-keys

2023-05-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        get(obj.getId());
`update` у `jdbcTemplate` возвращает число строк на которое он повлиял, если оно в данном случае равно нулю, то можно не делать дополнительный `get`, и уменьшить количество запросов к СУБД

2023-05-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +                throw new IllegalArgumentException("specialGet получил неверный ключ операции.");
Да, но непонятно зачем он даже на уровне хранилища, почему просто не сделать два разных метода. Если у них сильно разная логика и разное число аргументов.

2023-05-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/UserStorage.java
> +public class UserStorage implements Storage<User> {
Аналогичные замечания, что и в `ItemStorage`

2023-05-23 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        oldUser.mergeFrom(newUser);
Ок, я лично, предпочитаю, динамическим запросом в таком случае пользоваться, поэтому и не понял :)

https://stackoverflow.com/questions/7236654/jdbc-update-statement-non-null

2023-05-23 07:38 UTC, LexLippi commented on src/main/resources/schema.sql
> +        name_for_searching VARCHAR(32) NOT NULL, -- это поможет ПОЛНОСТЬЮ перенести поиск на базу данных.
ладно, давай оставим так

2023-05-24 00:03 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/Storage.java
> +    // сделать специфичное действие или что-то в этом роде.
Учту.

2023-05-24 00:04 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +        get(obj.getId());
Понял.

2023-05-24 00:07 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +                throw new IllegalArgumentException("specialGet получил неверный ключ операции.");
У меня `specialGet` является просто посредником между интерфейсом и другими методами хранилища. Я уже выбрал весьма специфичную (местами удобную) архитектуру интерфейса, по принципу "один для всех".

2023-05-24 00:08 UTC, DM-student commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto get(@PathVariable Long id) {
Хорошо.

2023-05-24 00:12 UTC, DM-student commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +            // уже выполняет задачу по ограничению добавления дубликата.
Я имел ввиду, что ограничение unique всегда будет выкидывать ошибку, если пытаешься записать дубликат. Я добавил пустой обработчик исключений для этой ошибки просто потому, что хочу чтобы оно само фильтровало и не пропускало дубликаты, по этому эта ошибка фактически игнорируется.

2023-05-24 09:34 UTC, LexLippi approved these changes
Привет!

Работу я приму, но насчет моего комментария подумай, хотелось бы в следующем спринте увидеть более разумную обработку этого исключения!

Желаю удачи!

2023-05-24 09:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/data/storage_implementation/ItemStorage.java
> +            // уже выполняет задачу по ограничению добавления дубликата.
Это я все прекрасно понял. Но тебе, как пользователю, не казалось бы странным игнорирование ошибки.
Ты на сайте добаляешь себе товар, у тебя успешно обновляется страница, но ничего не появляется в корзине. Ты делаешь так 5-10 раз, и расстраиваешься, что ничего не работает и уходишь. 

Потому что ошибку мы похоронили здесь на уровне обработки вставки в базу. Кажется, более корректным поведением было бы завершение http-метода с кодом ответа 409, который означает конфликт, чтобы фронтенд-разработчики которые взаимодействуют с нашим кодом могли как-то обработать эту ошибку и вывести пользователю красивое сообщение о том, что он делает не так, а для этого нам надо пробросить ошибку выше по стеку вызовов.

2023-05-26 00:22 UTC, merged