Реквесты и пагинация... Моки будут позже.
DM-student/java-shareit pull request #5
Opened 2023-06-13 04:48 UTC by DM-student

Здравствуйте, как вы наверное заметили - я ещё пока не прикрутил МокТесты. Их я реализую как только получу от вас "зелёный свет", и когда пойму, что мне не нужно будет серьёзно менять логику и прочее, чтобы не писать Моки по пусту и не тратить на это нервы и время.

2023-06-13 04:52 UTC, DM-student commented
Если что, сборка красная, ибо ругается на отсутствие тестов, которые я добавлю как только пойму, что мне не нужно будет всё переделывать...

2023-06-13 10:01 UTC, LexLippi requested changes
Привет!

Ок, неплохая работа, отписал пару комментариев, которые необходимо исправить!

Желаю удачи!

2023-06-13 10:01 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                   @Positive @RequestParam(required = false, defaultValue = "" + Integer.MAX_VALUE) Integer size,
`required=false` не нужен, там где есть `defaultValue`

2023-06-13 10:01 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    // переносить на БД, рефакторя всё под ноль...
Ок, давай оставим как есть, но это очень плохо, это сильно влияет на скорость выполнения запросов и на нагрузку на СУБД, мы вытягиваем каждый раз огромное количество лишних данных. В реальных проектах так делать нельзя :)

2023-06-14 05:09 UTC, DM-student commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    // переносить на БД, рефакторя всё под ноль...
Я знаю, что нельзя, но я просто не потяну сейчас тотальный рефакторинг...

2023-06-15 05:47 UTC, DM-student commented
Здравствуйте! Прошу прощения что вновь кидаю на проверку то, что ещё в процессе разработки. Мне бы хотелось узнать, устраивает ли вас мой метод интеграции юнит-тестов и могу ли я продолжать? Просто мне не хочется потратить много-много часов на то, чтобы потом услышать о том, что мною была выбрана не верная стратегия тестирования.

2023-06-15 08:13 UTC, LexLippi commented
Привет!

Да, все норм, можно использовать такую стратегию, жду уже полноценную работу :)

2023-06-16 12:03 UTC, DM-student commented
Вновь здравствуйте! Простите что ещё раз вас тревожу около-завершённым проектом, но у меня вновь возник вопрос именно к вам как к ревьюверу.

Дело в том, что в сборке стоял плагин, который был призван проверить объём тестирования но...
Но дело в том, что этот плагин в целом хочет чтобы чуть ли не каждый класс имел тесты, а также чтобы почти каждый метод был был протестирован...

Я считаю, что это очень глупо и бесполезно в плане затраты времени и нервов, ведь тесты всё же нужны там, где есть хоть какая-то логика, которую надо проверять, а не для каждого метода и класса... В общем итоге я снёс этот плагин, ибо считаю что нам виднее, какие классы и методы стоит покрыть тестами.
Также у меня немного сроки поджимают, и я с ума сойду прописывать тесты для каждого класса и метода...

Буду благодарен любому фидбеку и также буду рад, если вы поймёте меня и мою ситуацию.

2023-06-16 12:07 UTC, DM-student commented
Мне просто очень хотелось бы поскорее закрыть ТЗ, чтобы не прогореть...

2023-06-17 12:29 UTC, LexLippi commented
Привет, не согласен с тем, что тесты нужны там, где есть логика, поскольку нам часто необходимо понимать, что все компоненты работают так как надо. Не только те, в которых есть бизнес-логика, но и те, которые являются вспомогательными. Более того, раз это предусмотрено заданием, то рекомендую делать именно так.

А вообще с таким вопросом лучше обратиться к своему наставнику, если ты сможешь его убедить, то я приму работу с тем количеством тестов, которое есть.

2023-06-17 12:33 UTC, LexLippi reviewed
Привет!

В целом работа, ок, но по поводу количества тестов проконсультируйся с наставником, если он скажет, что нельзя, то надо их дописать.

Иначе приму работу в том виде, который есть.

Желаю удачи!

2023-06-17 14:59 UTC, DM-student commented
Собственно, получил добро от наставника. Благодарю вас за понимание. 
![opera_pXvbpOUYSM](https://github.com/DM-student/java-shareit/assets/111021008/a970163a-429d-457f-beee-b79781db7fc8)

2023-06-19 06:18 UTC, LexLippi commented
Привет!

Хорошая работа, жулаю удачи и не опаздывать в следующих спринтах!

2023-06-20 18:22 UTC, merged