Add docker
DM-student/java-shareit pull request #6
Opened 2023-06-29 02:44 UTC by DM-student

2023-06-29 04:29 UTC, DM-student commented
Здравствуйте! Хочу сразу сказать, что это был самый нервозный спринт из всех, что у меня был. Много новой информации и не самое вразумительное теоретическое сопровождение.

Заранее скажу, что я не ВООБЩЕ не трогал логику модуля серверной части, ибо ввиду спешки на прошлых спринтах, я мягко написал говоря не самый гибкий код, а на рефакторинг у меня времени особо не было и нет (в случае с текущим спринтом мягкого дедлайна нет, есть только жёсткий), так что прошу вас, по возможности пощадите мои нервы и время, ибо я сам понимаю, что в проекте много изъянов, и мне хочется поскорее закрыть этот проект, дабы не прогореть по срокам.

2023-06-29 18:24 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество комментариев, которые необходимо исправить!

Желаю удачи!

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingClient.java
> +                throw new ShareItProvidedDataException("Unknown state: UNSUPPORTED_STATUS", state);
Что? Зачем? Как?

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingClient.java
> +        }
Объедини в одно условие здесь и ниже

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingClient.java
> +        }
Такая вложенность это вообще ад :)

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingController.java
> +                                         @RequestParam(required = false, defaultValue = "ALL") String state) {
`defaultValue` подразумевает `required=false`, так что это бессмысленно

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingController.java
> +                                                 @RequestParam(required = false, defaultValue = "ALL") String state) {
Аналогично тому, что выше

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/item/ItemClient.java
> +            get("");
???
Сначала делаем такой `get("")`, а потом еще один с `userId = null`?

Очень странно выглядит

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/item/ItemClient.java
> +        }
в одно условие объединить здесь и ниже

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/request/ItemRequestClient.java
> +        }
В одно условие

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/request/ItemRequestController.java
> +                                         @RequestParam(required = false, defaultValue = "0") long from,
Про это уже писал

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/UserClient.java
> +        }
в одно условие

2023-06-29 18:24 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/utility/exceptions/ShareItBaseExceptionBaseException.java
> +            errorData = null;
По умолчанию и так инициализируется, в этом нет никакого смысла

2023-06-29 18:38 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingClient.java
> +                throw new ShareItProvidedDataException("Unknown state: UNSUPPORTED_STATUS", state);
Отсечь мусорные статусы.

2023-06-29 18:39 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingClient.java
> +        }
Хорошо

2023-06-29 19:09 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingClient.java
> +        }
Исправил.

2023-06-29 19:10 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/item/ItemClient.java
> +            get("");
Я забыл return добавить.

2023-06-29 19:12 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/request/ItemRequestClient.java
> +        }
Сделал.

2023-06-29 19:12 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/user/UserClient.java
> +        }
Сделал.

2023-06-29 19:14 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/utility/exceptions/ShareItBaseExceptionBaseException.java
> +            errorData = null;
Если я попробую "toString" на нулле, то вылетит ошибка...

2023-06-29 19:14 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/request/ItemRequestController.java
> +                                         @RequestParam(required = false, defaultValue = "0") long from,
Сделал.

2023-06-29 19:14 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/item/ItemClient.java
> +        }
Сделал.

2023-06-29 19:14 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingController.java
> +                                                 @RequestParam(required = false, defaultValue = "ALL") String state) {
Угу.

2023-06-29 19:15 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingController.java
> +                                         @RequestParam(required = false, defaultValue = "ALL") String state) {
Хорошо.

2023-06-30 07:02 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/gateway/utility/exceptions/ShareItBaseExceptionBaseException.java
> +            errorData = null;
`errorData`по умолчанию инициализируется `null`-ом, так что нет смысоа в том, что лежит внутри `else`

2023-06-30 07:03 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Оставил один маленький комментарий, поправь его и я приму работу!

Желаю удачи!

2023-06-30 19:32 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/utility/exceptions/ShareItBaseExceptionBaseException.java
> +            errorData = null;
А... Точно.

2023-06-30 19:46 UTC, DM-student commented on gateway/src/main/java/ru/practicum/shareit/gateway/utility/exceptions/ShareItBaseExceptionBaseException.java
> +            errorData = null;
Всё не совсем так. Я исправлю это замечание, но уточню причину, по которой это было так сделано.

2023-07-01 08:21 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи с дипломным проектом!

2023-07-06 21:42 UTC, merged